### PR TITLE
task1 beginner problem and solution added

### PR DESCRIPTION
**Pull request by salmanpary**

### CODE REVIEW

**Comment by salmanpary** [comment]
new problems added

**Comment by salmanpary** [comment]
reverse integer problem added.

**Review by Kushal997-das — COMMENTED** [review]
@salmanpary Add your details in data.json file .

@salmanpary don't forget  give a star to the repo 👍

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@salmanpary Add your details in data.json file .

@salmanpary don't forget give a star to the repo 👍

**Pull request closed without merging**
