### PR TITLE
Print 2D array in  spiral form

### PR DESCRIPTION
**Pull request by GV-Akhil-Chandra**
I added a new file with question "Print 2D array in spiral form".

### CODE REVIEW

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@GV-Akhil-Chandra There is some unnecessary file please remove

**Comment by GV-Akhil-Chandra** [comment]
Actually I am new to open source, can you be more specific about which files should I delete.

**Comment by Kushal997-das** [comment]
> Actually I am new to open source, can you be more specific about which files should I delete.

See others people @GV-Akhil-Chandra How they did .

**Comment by GV-Akhil-Chandra** [comment]
Hello @Kushal997-das  i have deleted the files.

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
Please add the details in data.json file

**Pull request closed without merging**
