### PR TITLE
new folder infix_to_postfix added in task_1 of begineer level

### PR DESCRIPTION
**Pull request by pratik-2707**

### CODE REVIEW

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@pratik-2707 add details in data.json file .

**Comment by pratik-2707** [comment]
but there it is writen that we cant edit that file

**Comment by pratik-2707** [comment]
changes done
name added in data.json file

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@pratik-2707 Add details under task 1 man .

**Pull request closed without merging**
